version : "3.8"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: qwerty
    volumes:
      - /d/user:/data/db

  mongo-express:
      image: mongo-express
      ports:
        - "8081:8081"
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: admin
        ME_CONFIG_MONGODB_ADMINPASSWORD: qwerty
        ME_CONFIG_MONGODB_SERVER: mongodb
      depends_on:
        - mongodb

  node-app:
    build: .
    ports:
      - "5050:5050"
    environment:
      MONGO_URL: mongodb://admin:qwerty@mongodb:27017/apnacollege-db?authSource=admin
    depends_on:
      - mongodb
  